CREATE TABLE IF NOT EXISTS users_verify(
    id     INTEGER PRIMARY KEY,
    userID INTEGER NOT NULL UNIQUE,
    token  TEXT    NOT NULL,
    FOREIGN KEY (userID) REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
